table _MeasureTable
	lineageTag: 47894e6e-3462-488b-abb7-4cf20d487757

	measure _cumulativeP50_new =
			
			
			var calc = CALCULATE(sum(fact_volumes[amount]), Filter(ALLSELECTED('dim_projects'), 'dim_projects'[DG3Index] <= Max('dim_projects'[DG3Index])))
			
			
			return calc
		lineageTag: 5027a3bf-187b-475f-96fd-046c7512ffeb

	column 1
		dataType: string
		lineageTag: 1d74e995-9215-4bb7-a55e-181bae5a1be4
		summarizeBy: none
		sourceColumn: 1

		annotation SummarizationSetBy = Automatic

	partition _MeasureTable = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WSlSKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"1" = _t])
				in
				  Source

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

