table Assets
	lineageTag: 8309cda9-224e-4040-852d-c1f8024763ef

	column Asset
		dataType: string
		lineageTag: d89195a1-6b14-4d97-a921-d980888713b0
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 19c2498d-9269-473d-97fa-21d2cff0f2d2
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Well
		dataType: string
		lineageTag: 8f092fb6-4682-4299-84e8-5ae47255bb60
		summarizeBy: none
		sourceColumn: Well

		annotation SummarizationSetBy = Automatic

	partition Assets = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZTBSsQwEIZfZel5sckkadPjiuJFQRAFWfYQsLSlcZW67vPbmWZLk6WJl9BO5puZ/0/a/T57M7Y11mbbjDNacH0yTX08mfHp1n71/QZyjXs3PDtsl0iFURUjICAwWhYRQARAiW1iHWQAYHHOVYRQRNx3DW4B1gbScGeGfvMw1PVxRniRc9x3yh3DUTeASjDgMdS7SjHCY0oCdYKRHlPQbDzBTB68WrJAUS9cn3+Hb1vP6WXOYXwRTr5Ll9Qmlg7LdDFfkrV0sUzHEJex6nKZzmkYHUmfpO7sua27T4xgbYlH6HsDKkdl0oldABRW6wCEAEoWeh0QIYCTSrYOyBCgUyzWgUn0S2+G86W0RgWPXdOegktRKFbmOIFy0i+YQJM0S2PgY/SR6zQmfAxve1GlMelj6IL6h7bJkvem+RjMT2cvZyr4/O2HPwzGaCTnikeiy4KpFAnXJN4NqKoUKa5JlAFlsqe8Jum2aEiRo0OHPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Asset = _t, Price = _t, Amount = _t, Color = _t, Location = _t, Level = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Price", Int64.Type}, {"Amount", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Asset", "Location"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"Asset"}),
				    #"Added Conditional Column" = Table.AddColumn(#"Removed Duplicates", "Well", each if [Asset] = "Valhall" then "Well_1" else if [Asset] = "Eiga" then "Well_2" else if [Asset] = "Ula" then "Well_3" else if [Asset] = "Alvheim" then "Well_4" else if [Asset] = "Skarv" then "Well_5" else if [Asset] = "Yggdrasil" then "Well_6" else null, type text)
				in
				    #"Added Conditional Column"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

