table 'Example data'
	lineageTag: 7e174f7c-5414-4570-b4a2-87e1f2595106

	measure 'Max of Price average per Price' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Example data'[Price])),
				CALCULATE(MAX('Example data'[Price]))
			)
		formatString: #,0
		lineageTag: ebfd0978-1e30-4550-aa47-723526e45dd2

	measure 'Price average per Location' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Example data'[Location])),
				CALCULATE(SUM('Example data'[Price]))
			)
		formatString: #,0
		lineageTag: d62be214-8662-48f2-b20f-fe747eea4445

	measure 'Price average per Country running total in Location' =
			
			CALCULATE(
				[Price average per Asset],
				FILTER(
					ALLSELECTED('Example data'[Asset]),
					ISONORAFTER('Example data'[Asset], MAX('Example data'[Location]), DESC)
				)
			)
		formatString: #,0
		lineageTag: 760444a2-c508-4b46-80d4-7437eed7528c

	measure 'Min of Price weighted by Count of Color per Asset' =
			
			VAR __CATEGORY_VALUES = VALUES('Example data'[Asset])
			RETURN
				DIVIDE(
					SUMX(
						KEEPFILTERS(__CATEGORY_VALUES),
						CALCULATE(MIN('Example data'[Price]) * COUNTA('Example data'[Color]))
					),
					SUMX(
						KEEPFILTERS(__CATEGORY_VALUES),
						CALCULATE(COUNTA('Example data'[Color]))
					)
				)
		formatString: #,0
		lineageTag: 57b2fe9a-3b19-47d0-9919-77ad734f7b92

	measure 'Price total for Asset' =
			
			CALCULATE(SUM('Example data'[Price]), ALL('Example data'[Color]))
		formatString: #,0
		lineageTag: ff89149e-d61b-40ce-83dc-3e4ccaf67087

	measure 'Price average per Asset' =
			
			AVERAGEX(
				KEEPFILTERS(VALUES('Example data'[Color])),
				CALCULATE(SUM('Example data'[Price]))
			)
		formatString: #,0
		lineageTag: 0a855f8a-7c7a-4a00-8332-f9cbb6eb757f

	column Price
		dataType: int64
		formatString: 0
		lineageTag: 1e15956e-b49b-455b-91c3-5eb4e20c26af
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: #,0
		lineageTag: a8031377-14ca-4f18-8248-4c33211d0609
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	column Color
		dataType: string
		lineageTag: 04531a95-13c5-4d63-a34e-8fc29725652c
		summarizeBy: none
		sourceColumn: Color

		annotation SummarizationSetBy = Automatic

	column Asset
		dataType: string
		lineageTag: 068d7004-3fcc-4f4d-9e3e-285ce2c18535
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: a7317991-115b-456a-814a-01aa6302b0c9
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Level
		dataType: string
		lineageTag: 02a3249b-d54a-4775-b07a-917c9f4932d8
		summarizeBy: none
		sourceColumn: Level

		annotation SummarizationSetBy = Automatic

	partition 'Example data' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZTBSsQwEIZfZel5sckkadPjiuJFQRAFWfYQsLSlcZW67vPbmWZLk6WJl9BO5puZ/0/a/T57M7Y11mbbjDNacH0yTX08mfHp1n71/QZyjXs3PDtsl0iFURUjICAwWhYRQARAiW1iHWQAYHHOVYRQRNx3DW4B1gbScGeGfvMw1PVxRniRc9x3yh3DUTeASjDgMdS7SjHCY0oCdYKRHlPQbDzBTB68WrJAUS9cn3+Hb1vP6WXOYXwRTr5Ll9Qmlg7LdDFfkrV0sUzHEJex6nKZzmkYHUmfpO7sua27T4xgbYlH6HsDKkdl0oldABRW6wCEAEoWeh0QIYCTSrYOyBCgUyzWgUn0S2+G86W0RgWPXdOegktRKFbmOIFy0i+YQJM0S2PgY/SR6zQmfAxve1GlMelj6IL6h7bJkvem+RjMT2cvZyr4/O2HPwzGaCTnikeiy4KpFAnXJN4NqKoUKa5JlAFlsqe8Jum2aEiRo0OHPw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Asset = _t, Price = _t, Amount = _t, Color = _t, Location = _t, Level = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Price", Int64.Type}, {"Amount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

