table Products
	lineageTag: 32cc45d0-3206-4f79-8d0a-bfbe652ad9bc

	measure 'Quantity Multiplied' =
			
			SUM( Products[Quantity] ) *10
		formatString: 0
		lineageTag: 18ce6a5b-d01b-4d38-8568-a69a91612a1a

	measure 'Amount Divided' =
			
			DIVIDE(
			    SUM( 'Example data'[Amount] ) ,
			    2 )
		lineageTag: efe20efe-bd29-4a64-8325-d455fb0af275

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product
		dataType: string
		lineageTag: bdd48c8f-ba45-4572-ae5a-ff63f8433340
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: #,0
		lineageTag: c5b8e1ef-487f-456c-902c-d4e1f0c0122c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Asset
		dataType: string
		lineageTag: c1187079-1d66-4985-ac17-7e7123e3fab9
		summarizeBy: none
		sourceColumn: Asset

		annotation SummarizationSetBy = Automatic

	partition Products = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZHLCoMwEEX/JWsX9dGqy1KKm9IuSgtFXAwYojS1oMXvb3QMuRJXM5xLcg9JWYpbq0UgnqQb0tMW7kQVWHxuFZmRAXroiaRAjnpsZPsxWwT0/qZ+NHMP7KVU3dMw7/nMT9+ult1AP7mSyPxwUYn9hI0SP3BioR9av41zqMkm1+Ky8ouALmIHQGyUA3EqCVDrEAPDcr6zoGHjcZiuyhlxeQzEladAbXkEDMvNx1V/", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Product = _t, Asset = _t, Quantity = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Quantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

