table Visuals
	isHidden
	lineageTag: d4a365cb-2729-4749-85b0-070e55416fa8

	measure 'Show Scatter Bar Chart' =
			
			IF(
			    SELECTEDVALUE( Visuals[Visual Type] )
			    = "Scatter Bar Chart" ,
			        1 ,
			        0
			)
		formatString: 0
		isHidden
		lineageTag: 600497e1-9b1f-47f7-bfd5-1e6ae910e2b5

		changedProperty = IsHidden

	column 'Visual Type Group'
		dataType: string
		isHidden
		lineageTag: eddf12ea-cfb9-48fb-b08d-0a797dc79ac7
		summarizeBy: none
		sourceColumn: Visual Type Group

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Type Group Explanation'
		dataType: string
		isHidden
		lineageTag: e406b033-a968-46d8-973c-88705034267f
		summarizeBy: none
		sourceColumn: Visual Type Group Explanation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Visual Type'
		dataType: string
		isHidden
		lineageTag: 0b97f99b-3104-4d73-81a6-a6825a45014b
		summarizeBy: none
		sourceColumn: Visual Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Viual Type Explanation'
		dataType: string
		isHidden
		lineageTag: dac21d72-2d71-402a-b45a-a3cb7be3012e
		summarizeBy: none
		sourceColumn: Viual Type Explanation

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Microsoft Docs'
		dataType: string
		isHidden
		lineageTag: 16e33dc6-1aa2-47a7-9c0b-c1b90fd40561
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: Microsoft Docs

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Visuals = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("7Vttjxu3Ef4rCwMFEkB757YfChQIgrMNB4fGjRE7aIM0H6hdSmK0u2RI7umUX59n", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Visual Type Group" = _t, #"Visual Type Group Explanation" = _t, #"Visual Type" = _t, #"Viual Type Explanation" = _t, #"Microsoft Docs" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Visual Type Group", type text}, {"Visual Type Group Explanation", type text}, {"Visual Type", type text}, {"Viual Type Explanation", type text}, {"Microsoft Docs", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

